OPENAI_API_KEY = "sk-2...X"

[connections.snowpark]
user = "<username>"
password = "<pass>"
warehouse = "MY_WH"
role = "MYROLE"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "MY ACCOUNT ID"
